//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public position()
        {
            this.user_data = new HashSet<user_data>();
        }

       
        public int id { get; set; }
        public string position_name { get; set; }
        public int priority { get; set; }
        public string description { get; set; }
        public string permission_ids { get; set; }
        public System.TimeSpan work_schedules { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_data> user_data { get; set; }                
    }
}
