//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_table
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<bool> paid_leave { get; set; }
        public Nullable<bool> sick_leave { get; set; }
        public System.DateTime update_at { get; set; }
    
        public virtual user_data user_data { get; set; }
    }
}
