//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_data()
        {
            this.news = new HashSet<news>();
            this.time_table = new HashSet<time_table>();
        }
    
        public int id { get; set; }
        public int personal_data_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> first_working_day { get; set; }
        public Nullable<System.DateTime> last_working_day { get; set; }
        public int position_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news> news { get; set; }
        public virtual personal_data personal_data { get; set; }
        public virtual position position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<time_table> time_table { get; set; }
    }
}
