//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userProjectDBContext : DbContext
    {
        public userProjectDBContext()
            : base("name=userProjectDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<personal_data> personal_data { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<time_table> time_table { get; set; }
        public virtual DbSet<user_data> user_data { get; set; }
    }
}
